/**
 * 管理侧「渠道配置」fixtures — 飞书 / 企业微信 / 钉钉 / Web 对话入口。
 */
import type {
  NotificationChannel,
  WebhookEntry,
  NotificationGroup,
  DeliveryEvent,
} from './schema';

export const mockChannels: NotificationChannel[] = [
  {
    id: 'ch-001',
    name: '飞书 · 客服助手',
    kind: 'feishu',
    status: 'active',
    target: '客服助手',
    description: '飞书客服群与私聊入口，接待客户咨询。',
    lastUsed: '5 分钟前',
    successRate: 99.4,
    sentToday: 86,
    config: { appId: 'cli_a1b2c3', appSecret: 'fs-****-9k2m', verificationToken: 'vt-****', encryptKey: '' },
    starred: true,
    scope: ['客服', '运营'],
    template: '你好，我是客服助手，可查询订单、知识库与工单进度。',
  },
  {
    id: 'ch-002',
    name: '飞书 · 内部助手',
    kind: 'feishu',
    status: 'draft',
    target: '内部助手',
    description: '飞书内部知识问答（草稿，尚未发布事件订阅）。',
    lastUsed: '从未',
    successRate: 0,
    sentToday: 0,
    config: { appId: 'cli_draft', appSecret: '', verificationToken: '', encryptKey: '' },
    starred: false,
    scope: ['内部'],
    template: '你好，我是内部助手。',
  },
  {
    id: 'ch-003',
    name: '企业微信 · 客服接待',
    kind: 'wecom',
    status: 'failed',
    target: '客服接待',
    description: '企业微信客服应用（最近一次鉴权失败）。',
    lastUsed: '昨天',
    successRate: 60.5,
    sentToday: 0,
    config: { corpId: 'ww-qzdap', agentId: '1000002', secret: 'wx-****', token: 'tk-****', encodingAesKey: '' },
    starred: false,
    scope: ['客服'],
    template: '你好，我是企业微信客服助手。',
  },
  {
    id: 'ch-004',
    name: '钉钉 · 运维值班',
    kind: 'dingtalk',
    status: 'paused',
    target: '运维值班机器人',
    description: '钉钉运维群机器人（暂已暂停）。',
    lastUsed: '3 天前',
    successRate: 95.2,
    sentToday: 0,
    config: { appKey: 'ding-ops', appSecret: 'dt-****', robotCode: 'robot-ops', corpId: 'ding-corp' },
    starred: false,
    scope: ['运维'],
    template: '你好，我是运维值班助手。',
  },
  {
    id: 'ch-005',
    name: '钉钉 · 销售助手',
    kind: 'dingtalk',
    status: 'active',
    target: '销售助手',
    description: '钉钉销售群对话，查询线索与报价。',
    lastUsed: '12 分钟前',
    successRate: 98.1,
    sentToday: 34,
    config: { appKey: 'ding-sales', appSecret: 'dt-****-s', robotCode: 'robot-sales', corpId: 'ding-corp' },
    starred: true,
    scope: ['销售'],
    template: '你好，我是销售助手，可查询线索、报价与合同模板。',
  },
  {
    id: 'ch-006',
    name: 'Web 工作台',
    kind: 'web',
    status: 'active',
    target: '工作台对话',
    description: '平台 Web 工作台内嵌对话窗口。',
    lastUsed: '1 分钟前',
    successRate: 99.9,
    sentToday: 142,
    config: { siteUrl: 'https://console.example.com', allowedOrigins: 'https://console.example.com', embedPath: '/copilot', widgetToken: 'wgt-****-a3f1' },
    starred: false,
    scope: ['全员'],
    template: '你好，我是企业智能助手。请直接在对话框里提问。',
  },
  {
    id: 'ch-007',
    name: 'Web 官网嵌入',
    kind: 'web',
    status: 'draft',
    target: '官网智能客服',
    description: '官网右下角嵌入窗口（草稿，尚未发布）。',
    lastUsed: '从未',
    successRate: 0,
    sentToday: 0,
    config: { siteUrl: 'https://www.example.com', allowedOrigins: 'https://www.example.com', embedPath: '/embed/chat', widgetToken: '' },
    starred: false,
    scope: ['官网'],
    template: '你好，欢迎咨询。',
  },
];

export const mockWebhooks: WebhookEntry[] = [
  { id: 'wh-001', name: 'CRM 同步', url: 'https://crm.example.com/api/qzdap', method: 'POST', secret: 'whsec-****-a3f1', eventFilter: ['agent.session.completed', 'agent.session.failed'], enabled: true, lastDelivery: '1 分钟前', status: 'success', retry: 0 },
  { id: 'wh-002', name: '审计日志归档', url: 'https://audit.example.com/ingest', method: 'POST', secret: 'whsec-****-b4e2', eventFilter: ['audit.*'], enabled: false, lastDelivery: '—', status: 'pending', retry: 0 },
  { id: 'wh-003', name: '告警回写服务', url: 'https://alert.example.com/callback', method: 'PUT', secret: 'whsec-****-c8d0', eventFilter: ['alert.fired'], enabled: true, lastDelivery: '昨天', status: 'failed', retry: 3 },
];

export const mockGroups: NotificationGroup[] = [
  { id: 'gp-001', name: '全员运营组', description: '覆盖客服、运营入口的值班人员。', members: [{ name: '张敏', channel: 'feishu', address: '客服助手' }, { name: '李雷', channel: 'web', address: '工作台对话' }, { name: '王芳', channel: 'wecom', address: '客服接待' }], rules: 6 },
  { id: 'gp-002', name: '运维 OnCall', description: '7x24 接收运维会话与升级。', members: [{ name: '陈昊', channel: 'dingtalk', address: '运维值班机器人' }, { name: '刘琪', channel: 'feishu', address: '内部助手' }], rules: 12 },
  { id: 'gp-003', name: '销售协作组', description: '销售助手与 Web 嵌入的值班配置。', members: [{ name: '韩雪', channel: 'dingtalk', address: '销售助手' }, { name: '官网值班', channel: 'web', address: '官网智能客服' }], rules: 3 },
];

export const mockEvents: DeliveryEvent[] = [
  { id: 'ev-001', channelId: 'ch-001', channelName: '飞书 · 客服助手', kind: 'feishu', subject: '客户询问退款进度', recipient: '飞书 · 张敏', status: 'delivered', deliveredAt: '今天 09:14' },
  { id: 'ev-002', channelId: 'ch-006', channelName: 'Web 工作台', kind: 'web', subject: '查询本周用量', recipient: '工作台 · 管理员', status: 'delivered', deliveredAt: '今天 09:14' },
  { id: 'ev-003', channelId: 'ch-003', channelName: '企业微信 · 客服接待', kind: 'wecom', subject: '鉴权失败:access_token 无效', recipient: '企业微信 · 客服', status: 'failed', deliveredAt: '今天 09:11', error: 'access_token 已过期' },
  { id: 'ev-004', channelId: 'ch-005', channelName: '钉钉 · 销售助手', kind: 'dingtalk', subject: '线索跟进提醒', recipient: '钉钉 · 销售群', status: 'delivered', deliveredAt: '今天 09:08' },
  { id: 'ev-005', channelId: 'ch-001', channelName: '飞书 · 客服助手', kind: 'feishu', subject: '知识库检索：差旅标准', recipient: '飞书 · 李楠', status: 'delivered', deliveredAt: '昨天 09:00' },
  { id: 'ev-006', channelId: 'ch-004', channelName: '钉钉 · 运维值班', kind: 'dingtalk', subject: '通道暂停中', recipient: '钉钉 · 运维群', status: 'queued', deliveredAt: '今天 09:00' },
];
